### ISSUE TITLE
Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-ObjeX#12]
- [x] Deve ser inserido o líder estelar
- [x] onde estão os artefatos citados na Matriz de Comunicação: Ata de reunião , Relatório de situação do projeto, Relatório de tarefas a serem realizadas no dia, etc.

**Comment by cwtshh** [comment]
Correções efetivadas! Obrigado, Professor!
