### ISSUE TITLE
PBB

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-ObjeX#66]
- a estrutura está correta
- Ajustes a serem feitos:
- [x] não se repete o nome da feature no quadro de PBIs
- [x] algumas Features e PBIs estão inconsistentes, exemplos:
![image](https://github.com/user-attachments/assets/6f9faf01-d4d2-45cf-8d09-4059f231393a)
![image](https://github.com/user-attachments/assets/c7aa9c34-c8df-49ec-8afe-0273b823ab3f)
![image](https://github.com/user-attachments/assets/3889a209-348b-4b8b-89bb-f1477237f4c5)

**Comment by cwtshh** [comment]
Devidamente corrido. Obrigado pelo feedback professor!
