### ISSUE TITLE
USM

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-ObjeX#69]
- O USM possui uma boa estrutura
- os objetivos estão coerentes
- algumas atividades estão em um nível de granularidade muito baixo, o que faz com que as US fiquem pequenas demais, quase campo a campo. revejam isso. Exemplo:
![image](https://github.com/user-attachments/assets/f00982d4-c62e-4f58-ae07-bfcb4d6ba547)

- Existem US iguais em diferentes locais (personas e atividades). Isso é incorreto. Exemplos
Criar anúncio, enviar anúncio, estabelecer termos do anúncio

**Comment by cwtshh** [comment]
Devidamente corrigdo. Obrigado pelo feedback, Professor!
