### ISSUE TITLE
Declaração de Posição do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-ObjeX#8]
- [x] Ao invés de "Professor Henrique Gomes de Moura", colocar professor da disciplina Orientação a Objetos

- [x] Ao invés de "Estudantes da Disciplina", colocar estudantes da disciplina Orientação a Objetos, do curso de engenharia de software, UnB

**Comment by cwtshh** [comment]
Obrigado, Professor!
Mudanças feitas.
